from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class PlatformStatistics(BaseModel):
    """Platform-wide statistics model"""
    total_users: int = Field(default=0, description="Total number of registered users")
    total_courses: int = Field(default=0, description="Total number of available courses")
    total_conversations: int = Field(default=0, description="Total number of conversations")
    total_messages: int = Field(default=0, description="Total number of messages exchanged")
    total_study_guides: int = Field(default=0, description="Total number of study guides generated")
    total_practice_questions: int = Field(default=0, description="Total number of practice questions generated")
    total_knowledge_gaps: int = Field(default=0, description="Total number of knowledge gap assessments")
    active_users_last_day: int = Field(default=0, description="Number of users active in the last 24 hours")
    active_users_last_week: int = Field(default=0, description="Number of users active in the last 7 days")
    active_users_last_month: int = Field(default=0, description="Number of users active in the last 30 days")
    last_updated: datetime = Field(default_factory=datetime.utcnow, description="Last time the statistics were updated")


class CourseStatistics(BaseModel):
    """Course-specific statistics model"""
    course_id: str = Field(..., description="Course ID")
    course_name: str = Field(..., description="Course name")
    enrolled_students: int = Field(default=0, description="Number of students enrolled in the course")
    total_conversations: int = Field(default=0, description="Total conversations related to this course")
    total_messages: int = Field(default=0, description="Total messages exchanged about this course")
    total_study_guides: int = Field(default=0, description="Total study guides generated for this course")
    total_practice_questions: int = Field(default=0, description="Total practice questions for this course")
    total_knowledge_gaps: int = Field(default=0, description="Total knowledge gap assessments for this course")
    active_students_last_week: int = Field(default=0, description="Students active in the last 7 days")
    active_students_last_month: int = Field(default=0, description="Students active in the last 30 days")
    most_discussed_topics: List[Dict[str, Any]] = Field(default_factory=list, description="Most discussed topics")
    most_difficult_topics: List[Dict[str, Any]] = Field(default_factory=list, description="Topics with highest knowledge gaps")
    last_updated: datetime = Field(default_factory=datetime.utcnow, description="Last time the statistics were updated")


class UserStatistics(BaseModel):
    """User-specific statistics model"""
    user_id: str = Field(..., description="User ID")
    courses_enrolled: int = Field(default=0, description="Number of courses the user is enrolled in")
    total_conversations: int = Field(default=0, description="Total conversations by the user")
    total_messages: int = Field(default=0, description="Total messages sent by the user")
    total_study_guides: int = Field(default=0, description="Total study guides generated by the user")
    total_practice_questions: int = Field(default=0, description="Total practice questions generated by the user")
    total_knowledge_gaps: int = Field(default=0, description="Total knowledge gap assessments by the user")
    last_active: Optional[datetime] = Field(default=None, description="Last time the user was active")
    average_session_duration: Optional[int] = Field(default=None, description="Average session duration in minutes")
    total_study_time: Optional[int] = Field(default=None, description="Total study time in minutes")
    strongest_topics: List[Dict[str, Any]] = Field(default_factory=list, description="Topics with lowest knowledge gaps")
    weakest_topics: List[Dict[str, Any]] = Field(default_factory=list, description="Topics with highest knowledge gaps")
    last_updated: datetime = Field(default_factory=datetime.utcnow, description="Last time the statistics were updated")


class TimeSeriesDataPoint(BaseModel):
    """Time series data point for historical statistics"""
    timestamp: datetime = Field(..., description="Timestamp for this data point")
    value: float = Field(..., description="Value at this timestamp")


class TimeSeriesStatistic(BaseModel):
    """Time series statistic for tracking trends"""
    metric_name: str = Field(..., description="Name of the metric being tracked")
    metric_type: str = Field(..., description="Type of metric (count, percentage, etc.)")
    data_points: List[TimeSeriesDataPoint] = Field(default_factory=list, description="Historical data points")
    last_updated: datetime = Field(default_factory=datetime.utcnow, description="Last time the statistics were updated")


class StatisticsResponse(BaseModel):
    """Base response model for statistics endpoints"""
    success: bool = Field(default=True, description="Whether the request was successful")
    data: Dict[str, Any] = Field(default_factory=dict, description="The statistics data")


class PublicStatistics(BaseModel):
    """Public statistics that don't require authentication"""
    total_users: int = Field(..., description="Total number of registered users")
    total_courses: int = Field(..., description="Total number of available courses")
    total_conversations: int = Field(..., description="Total number of conversations")
    total_study_guides: int = Field(..., description="Total number of study guides generated")
    total_practice_questions: int = Field(..., description="Total number of practice questions generated")
    active_courses: List[Dict[str, Any]] = Field(default_factory=list, description="Most active courses")
    last_updated: datetime = Field(..., description="Last time the statistics were updated")